---
title: "Reproducible Research: Peer Assessment 1"
author: "Martin Sl?va"
date: "2018-02-28"
output: 
  html_document:
    keep_md: true
    
---


## Loading and preprocessing the data

```{r}
unzip(zipfile = "activity.zip") 
activity<-read.csv("activity.csv") 

```


## What is mean total number of steps taken per day?



```{r}
steps_sum<-with(activity, tapply(steps, date, FUN = sum, na.rm=T)) ### sum steps made every day

hist(steps_sum, breaks = 20, main="Total number of steps taken per day", xlab = "Number of steps", ylab = "Number of days" )


```


```{r mean_median}

steps_mean<- mean(steps_sum)

steps_median<- median(steps_sum)

```

The mean of steps per day is `r steps_mean` and median is `r steps_median`.



## What is the average daily activity pattern?



```{r}

steps_interval<-with(activity, aggregate(steps, list(interval),FUN=mean, na.rm=T )) ### 
names(steps_interval)<-c("Interval","Steps")
plot(steps_interval$Interval,steps_interval$Steps, type = "l", xlab = "Interval  - hhmm", ylab = "Average number of steps", main = "Average number of steps accross 5 minute intervals")
steps_interval$Interval[which.max(steps_interval$Steps)]


```


## Imputing missing values




```{r number_na}

number_na<-sum(is.na(activity))

```

Number of missing values is `r number_na`.


```{r}

steps_interval_median<-with(activity, tapply(steps, interval,FUN=median, na.rm=T ))     ### calculation of median for all interval - NA excluded
steps_na<-which(is.na(activity$steps))                                                  ### finding which rows have NA in steps column
activity_new<-activity                                                                  ### creating new variable
for(i in steps_na) {activity_new$steps[i]<-steps_interval_median[[1+activity$interval[i]%/%100*12+activity$interval[i]%%100/5]]}  ### replacement the NA by calculated median


```

```{r}
steps_sum_new<-with(activity_new, tapply(steps, date, FUN = sum, na.rm=T))

hist(steps_sum_new, breaks = 20, main="Total number of steps taken per day after missing value inputed ", xlab = "Number of steps", ylab = "Number of days" )


```



```{r mean_new}

 mean(steps_sum_new)

```


```{r median_new}

 median(steps_sum_new)

```





## Are there differences in activity patterns between weekdays and weekends?



```{r}

activity_new$weekend<-(weekdays(as.Date(activity_new$date)) ==weekdays(as.Date("2018-02-25")) | weekdays(as.Date(activity_new$date)) ==weekdays(as.Date("2018-02-24")))

steps_interval_new<-with(activity_new, aggregate(steps, by=list(interval,weekend),FUN=mean))
par(mfrow=c(2,1))
plot(steps_interval_new[steps_interval_new[,2],1], steps_interval_new[steps_interval_new[,2],3], type = "l", main="Average number of steps taken during weekends", xlab = "Time (hhmm)", ylab = "Number of steps")
plot(steps_interval_new[!steps_interval_new[,2],1], steps_interval_new[!steps_interval_new[,2],3], type = "l", main="Average number of steps taken during weekdays", xlab = "Time (hhmm)", ylab = "Number of steps")



```

